config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'speakers#index'

  resources :sponsors do 
  	resources :comments
  end

  resources :speakers do
  	resources :comments
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :commentable, polymorphic: true
end

app/models/speaker.rb
class Speaker < ApplicationRecord
  has_many :comments, as: :commentable
  validates :name, :place, :blog, :presence => {:message => 'This field is required.'}
end

app/models/sponsor.rb
class Sponsor < ApplicationRecord
  has_many :comments, as: :commentable
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :load_commentable

  def index
  	 @comments = @commentable.comments
  end

  def new
  	@comment = @commentable.comments.new
  end

	def create
	  @comment = @commentable.comments.new(comment_params)  
	  if @comment.save
	    redirect_to [@commentable, :comments], notice: 'Comment created'
	  else
	    render :new
	  end
	end

  private

  def comment_params
    params.require(:comment).permit!
  end

  def load_commentable
  	resource, id = request.path.split('/')[1,2]
  	@commentable = resource.singularize.classify.constantize.find(id)
  end
end

app/controllers/speakers_controller.rb
class SpeakersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_speaker, only: [:show, :edit, :update, :destroy]

  # GET /speakers
  # GET /speakers.json
  def index
    @speakers = Speaker.all
  end

  # GET /speakers/1
  # GET /speakers/1.json
  def show
  end

  # GET /speakers/new
  def new
    @speaker = Speaker.new
  end

  # GET /speakers/1/edit
  def edit
  end

  # POST /speakers
  # POST /speakers.json
  def create
    @speaker = Speaker.new(speaker_params)

    respond_to do |format|
      if @speaker.save
        format.html { redirect_to @speaker, notice: 'Speaker was successfully created.' }
        format.json { render :show, status: :created, location: @speaker }
      else
        format.html { render :new }
        format.json { render json: @speaker.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /speakers/1
  # PATCH/PUT /speakers/1.json
  def update
    respond_to do |format|
      if @speaker.update(speaker_params)
        format.html { redirect_to @speaker, notice: 'Speaker was successfully updated.' }
        format.json { render :show, status: :ok, location: @speaker }
      else
        format.html { render :edit }
        format.json { render json: @speaker.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /speakers/1
  # DELETE /speakers/1.json
  def destroy
    @speaker.destroy
    respond_to do |format|
      format.html { redirect_to speakers_url, notice: 'Speaker was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_speaker
      @speaker = Speaker.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def speaker_params
      params.require(:speaker).permit(:name, :place, :blog)
    end
end

app/controllers/sponsors_controller.rb
class SponsorsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_sponsor, only: [:show, :edit, :update, :destroy]

  # GET /sponsors
  # GET /sponsors.json
  def index
    @sponsors = Sponsor.all
  end

  # GET /sponsors/1
  # GET /sponsors/1.json
  def show
  end

  # GET /sponsors/new
  def new
    @sponsor = Sponsor.new
  end

  # GET /sponsors/1/edit
  def edit
  end

  # POST /sponsors
  # POST /sponsors.json
  def create
    @sponsor = Sponsor.new(sponsor_params)

    respond_to do |format|
      if @sponsor.save
        format.html { redirect_to @sponsor, notice: 'Sponsor was successfully created.' }
        format.json { render :show, status: :created, location: @sponsor }
      else
        format.html { render :new }
        format.json { render json: @sponsor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sponsors/1
  # PATCH/PUT /sponsors/1.json
  def update
    respond_to do |format|
      if @sponsor.update(sponsor_params)
        format.html { redirect_to @sponsor, notice: 'Sponsor was successfully updated.' }
        format.json { render :show, status: :ok, location: @sponsor }
      else
        format.html { render :edit }
        format.json { render json: @sponsor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sponsors/1
  # DELETE /sponsors/1.json
  def destroy
    @sponsor.destroy
    respond_to do |format|
      format.html { redirect_to sponsors_url, notice: 'Sponsor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sponsor
      @sponsor = Sponsor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sponsor_params
      params.require(:sponsor).permit(:name, :place, :blog)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/speakers_helper.rb
module SpeakersHelper
end

app/helpers/sponsors_helper.rb
module SponsorsHelper
end

app/views/comments/_form.html.erb
<%= form_for ([@commentable,@comment]) do |comment| %>
  <p>
    <%= comment.label "Name" %>
    <%= comment.text_field :name %>
  </p>
  
   <p>
    <%= comment.submit "Submit" %>
  </p>
<% end %>

app/views/comments/edit.html.erb
<h1>Edit comment</h1>
<%= render 'form' %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>comments</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.name %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if params[:speaker_id].present? %>
  <%= link_to 'back', speakers_path %>
<% else %>
  <%= link_to 'Back', sponsors_path %>
<% end %> 

app/views/comments/new.html.erb
<h1>New Comment</h1>
<%= render 'form' %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @comment.name %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Polymorphic</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>

    <div class="collapse navbar-collapse" id="navbar-collapse-1">
      <% if current_user.present? %>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Logout", destroy_user_session_path, method: :delete,:data => { confirm: 'Are you sure, you want to Logout?.'} %></li>
        </ul>
      <% end %>
    </div>
  </body>
</html>

app/views/speakers/_form.html.erb
<%= form_with(model: speaker, local: true) do |form| %>
  <% if speaker.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(speaker.errors.count, "error") %> prohibited this speaker from being saved:</h2>

      <ul>
      <% speaker.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :place %>
    <%= form.text_field :place %>
  </div>

  <div class="field">
    <%= form.label :blog %>
    <%= form.text_field :blog %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/speakers/edit.html.erb
<h1>Editing Speaker</h1>

<%= render 'form', speaker: @speaker %>

<%= link_to 'Show', @speaker %> |
<%= link_to 'Back', speakers_path %>

app/views/speakers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Speakers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Place</th>
      <th>Blog</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @speakers.each do |speaker| %>
      <tr>
        <td><%= speaker.name %></td>
        <td><%= speaker.place %></td>
        <td><%= speaker.blog %></td>
        <td><%= link_to 'comment', new_speaker_comment_path(speaker.id) %>
        <td><%= link_to 'Show', speaker %></td>
        <td><%= link_to 'Edit', edit_speaker_path(speaker) %></td>
        <td><%= link_to 'Destroy', speaker, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Speaker', new_speaker_path %>

<%= link_to 'Sponsors', sponsors_path %>

app/views/speakers/new.html.erb
<h1>New Speaker</h1>

<%= render 'form', speaker: @speaker %>

<%= link_to 'Back', speakers_path %>

app/views/speakers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @speaker.name %>
</p>

<p>
  <strong>Place:</strong>
  <%= @speaker.place %>
</p>

<p>
  <strong>Blog:</strong>
  <%= @speaker.blog %>
</p>

<%= link_to 'Edit', edit_speaker_path(@speaker) %> |
<%= link_to 'Back', speakers_path %>

app/views/sponsors/_form.html.erb
<%= form_with(model: sponsor, local: true) do |form| %>
  <% if sponsor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sponsor.errors.count, "error") %> prohibited this sponsor from being saved:</h2>

      <ul>
      <% sponsor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :place %>
    <%= form.text_field :place %>
  </div>

  <div class="field">
    <%= form.label :blog %>
    <%= form.text_field :blog %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/sponsors/edit.html.erb
<h1>Editing Sponsor</h1>

<%= render 'form', sponsor: @sponsor %>

<%= link_to 'Show', @sponsor %> |
<%= link_to 'Back', sponsors_path %>

app/views/sponsors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Sponsors</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Place</th>
      <th>Blog</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sponsors.each do |sponsor| %>
      <tr>
        <td><%= sponsor.name %></td>
        <td><%= sponsor.place %></td>
        <td><%= sponsor.blog %></td>
        <td><%= link_to 'comment', new_sponsor_comment_path(sponsor.id) %>
        <td><%= link_to 'Show', sponsor %></td>
        <td><%= link_to 'Edit', edit_sponsor_path(sponsor) %></td>
        <td><%= link_to 'Destroy', sponsor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sponsor', new_sponsor_path %>
<%= link_to 'Speakers', speakers_path %>

app/views/sponsors/new.html.erb
<h1>New Sponsor</h1>

<%= render 'form', sponsor: @sponsor %>

<%= link_to 'Back', sponsors_path %>

app/views/sponsors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @sponsor.name %>
</p>

<p>
  <strong>Place:</strong>
  <%= @sponsor.place %>
</p>

<p>
  <strong>Blog:</strong>
  <%= @sponsor.blog %>
</p>

<%= link_to 'Edit', edit_sponsor_path(@sponsor) %> |
<%= link_to 'Back', sponsors_path %>